### ISSUE TITLE
运行报错“OSError: [Errno 22] Invalid argument: ”是什么原因？

### ISSUE THREAD

**Issue by chensk1995** [LeLe86/vWeChatCrawl#15]
887 of 1176 20200425_171823_2 十幅心理漫画：揭示亲密关系的真相
 down imgs ▇▇  2Traceback (most recent call last):
  File "start.py", line 294, in <module>
    DownHtmlMain(jsdir, saveHtmlDir)
  File "start.py", line 211, in DownHtmlMain
    arthtmlstr = ChangeImgSrc(arthtmlstr, saveImgDir, artname)
  File "start.py", line 107, in ChangeImgSrc
    DownImg(originalURL, imgsavepath)
  File "start.py", line 79, in DownImg
    with open(savepath, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'E:/exportWechat/vWeChatCrawl-master/html/images\\20200425_171823_2_2.jpeg?x-oss-process=style/xmorient'

**Comment by LeLe86** [comment]
大哥，你需要有自己解决这种小而具体的问题的能力。最次最次，会跳过某些偶发异常的。
